name: tests
on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches: [ main ]
    paths-ignore:
      - "**.md"

  schedule:
    - cron: '25 08 * * *'

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Enable remote debugging session
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-26.04-arm]
        ddev_version: [stable, HEAD]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Environment setup
        run: |
          (sudo apt-get update >/dev/null || true) && sudo apt-get install -y expect >/dev/null

      - uses: ddev/github-action-add-on-test@v2
        with:
          ddev_version: ${{ matrix.ddev_version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          debug_enabled: ${{ github.event.inputs.debug_enabled }}
          addon_repository: ${{ env.GITHUB_REPOSITORY }}
          addon_ref: ${{ env.GITHUB_REF }}
